name: gpuweb_js
description: WebGPU bindings for Dart on the web.
version: 0.1.0
repository: https://github.com/dartgfx/gpux
topics:
  - gpu
  - webgpu
  - web

resolution: workspace
environment:
  sdk: ^3.10.0


dependencies:
  gpuweb: ^0.1.0
  meta: ^1.16.0

dev_dependencies:
  lints: ^5.1.1
